config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "static_pages#home"

  resources :todo_lists do 
  	resources :todo_items do 
  		member do
  			put :check_item
  		end
  	end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    


  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :todo_list
  belongs_to :user
  self.table_name = "todo_items"


 

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :user
  has_many :todo_items, dependent: :destroy
  self.table_name = "todo_lists"
  accepts_nested_attributes_for :todo_items, reject_if: :all_blank

  COLORS = ["Red", "Blue", "Green", "Yellow"]


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_lists
  has_many :todo_items
  after_commit :set_default_role, on: :create 

  private

  def set_default_role
  	self.role ||= "User"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include CanCan::ControllerAdditions
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		@todo_item = TodoItem.new
		@user = current_user
		
	end

	def new_list 
		@user = current_user
		@todo_list = @user.todo_lists.new
		if @todo_list.save
			redirect_to root_url
		else
			render 'new'
		end
	end


end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

	before_action :set_todo_list

	def new
		@todo_item = TodoItem.new
	end

	def create
		@todo_item = @todo_list.todo_items.new(todo_item_params)
		@todo_item.save
		redirect_to root_url
	end

	def destroy
		@todo_item = TodoItem.find(params[:id])
		@todo_item.destroy
		redirect_to root_url
	end

	def edit
		@todo_item = TodoItem.find(params[:id])
	end

	def update
		@todo_item = TodoItem.find(params[:id])
		if @todo_item.update_attributes(todo_item_params)
			redirect_to :back
		else
			render 'edit'
		end
	end

	def check_item
	  	@todo_item = TodoItem.find(params[:id])
	  	@todo_item.update_attributes(checked: true)
	  	redirect_to root_url
	end

	private

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def todo_item_params
		params.require(:todo_item).permit(:content, :importance, :due_date, :checked)
	end


end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
	before_action :set_user

	def new
		@user = current_user
		@todo_list = @user.todo_lists.new
	end

	def create
		@user = current_user
		@todo_list = @user.todo_lists.new(todo_list_params)
		if @todo_list.save
			redirect_to root_url
		else
			render 'new'
		end
	end

	def show
		@todo_list = TodoList.find(params[:id])
		@todo_item = TodoItem.new
	end

	def edit
		@user = current_user
		@todo_list = TodoList.find(params[:id])
	end

	def update
		@user = current_user
		@todo_list = TodoList.find(params[:id])
		if @todo_list.update_attributes(todo_list_params)
			redirect_to root_url
		else
			render 'edit'
		end
	end

	def destroy
		@todo_list = TodoList.find(params[:id])
		@todo_list.destroy
		redirect_to root_url
	end

	private

	def todo_list_params
		params.require(:todo_list).permit(:list_type, :title, :remove_self, :color,
			todo_items_attributes: [:content, :importance, :due_date, :checked])
	end
	
	def set_user
		@user = current_user
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper

	def list_background(list)
		if list.color == "Blue"
			"blue_background"
		elsif list.color == "Red"
			"red_background"
		elsif list.color == "Green"
			"green_background"
		elsif list.color == "Yellow"
			"yellow_background"
		else
			"list"
		end
	end

	

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class = "header">

		<img class = "header-img" src="">

		<div class = "header-right">
				<ul class = "header-nav-ul">

					<%= link_to "Home", root_url, class: "header-nav-li" %>
					<%= link_to "About", root_url, class: "header-nav-li" %>

					<% if user_signed_in? %>

						<%= link_to "Lists", new_user_registration_path, class: "header-nav-li" %>
						<%= link_to "Logout", destroy_user_session_path, method: :delete, class: "header-nav-li" %>

					<% else %>

						<%= link_to "Sign Up", new_user_registration_path, class: "header-nav-li" %>
						<%= link_to "Log In", new_user_session_path, class: "header-nav-li" %>

					<% end %>
				</ul>
		</div>

</header>

	<%= yield %>

</body>
</html>

app/views/static_pages/_homepage_description1.html.erb
<div class = "homepage_description1_hero">

	<div class = "homepage_description1-inner">


	</div>

</div>

app/views/static_pages/home.html.erb
<div class = "hero">

	<% if user_signed_in? %>
		
		<div class = "hero-inner_signed_in">
			
			<h1 class = "hero-title">You have <%= current_user.todo_lists.count %>

				<%= link_to "Lists", '#', class: "hero-title-strong" %>,</h1>

			<h1 class = "hero-title">and <%= current_user.todo_items.count %> <strong class = "hero-title-strong">

				<% if current_user.todo_items.count == 1 %>

					<%= link_to "Thing", '#', class: "hero-title-strong" %>

				<% else %>

					<%= link_to "Things", '#', class: "hero-title-strong" %>

				<% end %>

			to do</strong>.</h1>
			<h1 class = "hero-title"><%= link_to "Add List", "#", class: "root-add-list" %></h1>

		</div>

	<% else %>

		<div class = "hero-inner">

			<h1 class = "hero-title">Make your lists <strong class = "hero-title-strong">Doable</strong>.</h1>

		</div>

	<% end %>
			
</div>

<% if user_signed_in? %>

			<div class = "root-list-form">
					

					<div class = "hero">


					<%= render 'todo_lists/homepage_form' %>

			</div>

		</div>

	<div class = "main-content group">

		<% @user.todo_lists.each do |todo_list| %>

			<%= render 'todo_lists/todo_list', todo_list: todo_list %>

		<% end %>

	</div>

<% else %>

	<div class = "main-content-logged_out" >

		<%= render "static_pages/homepage_description1" %>

	</div>

<% end %>
	

app/views/todo_items/_form.html.erb
<%= form_for [@todo_list, @todo_item] do |f| %>

	<%= f.label :content %>
	<%= f.text_field :content %>

<% end %>

app/views/todo_items/_todo_item.html.erb
<div class = "list-item group">

	<%= form_tag check_item_todo_list_todo_item_path(todo_list, todo_item), method: :put, class: "list-item-checker group" do %>

		<%= submit_tag "Y" %>

	<% end %>

	<div class = "list-item-content group">

		<p class = "list-item-content-words"><%= todo_item.content %></p>

	</div>

</div>

app/views/todo_items/edit.html.erb
<%= render 'form' %>

app/views/todo_items/new.html.erb
<%= render 'form' %>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list do |f| %>

	<div class = "form-fields">

		<%= f.label :title, "Title *", class: "form-label" %>
		<%= f.text_field :title, class: "form-field" %>

		<br>

		<%= f.label :list_type, "Type", class: "form-label" %>
		<%= f.text_field :list_type, class: "form-field" %>

		<br>

		<%= f.label :remove_self, "Remove after all items are complete?", class: "form-label" %>
		<%= f.check_box :remove_self, class: "form-field" %>
		<br>

		<%= f.label :color, "Color", class: "form-label" %>
		<%= f.select :color, options_for_select(TodoList::COLORS, @todo_list.color), class: "form-field" %>

		<%= f.submit "Create List" %>

	</div>


<% end %>

app/views/todo_lists/_homepage_form.html.erb
<%= form_for TodoList.new do |f| %>

	<div class = "form-fields">

		<%= f.label :title, "Title *", class: "form-label" %>
		<%= f.text_field :title, class: "form-field" %>

		<br>

		<%= f.label :list_type, "Type", class: "form-label" %>
		<%= f.text_field :list_type, class: "form-field" %>

		<br>

		<%= f.label :remove_self, "Remove after all items are complete?", class: "form-label" %>
		<%= f.check_box :remove_self, class: "form-field" %>

		<br>

		<%= f.label :color, "Color", class: "form-label" %>
		<%= f.select :color, options_for_select(TodoList::COLORS), class: "form-field" %>

		<%= f.submit "Create List" %>

	</div>

<% end %>

app/views/todo_lists/_todo_list.html.erb
<div class = <%= list_background(todo_list) %> >

	<%= link_to "E", edit_todo_list_path(todo_list), class: "list-delete", todo_list: todo_list %>
	<%= link_to "X", todo_list_path(todo_list), method: :delete, class: "list-delete" %>

	<br>

	<div class = "list-header group">
		<%= link_to todo_list.title, todo_list_path(todo_list), class: "list-title" %>
		<p class = "list-type"><%= todo_list.list_type %></p>
	</div>

	<%= form_for [todo_list, @todo_item] do |f| %>
		
		<%= f.text_field :content, class: "new_item_box" %>
		<%= f.submit "+", class: "new_item_box_submit" %>

	<% end %>
	<br>

	<% todo_list.todo_items.where('checked = 0').order(created_at: :desc).each do |todo_item| %>

		<%= render 'todo_items/todo_item', todo_item: todo_item, todo_list: todo_list %>

	<% end %>

</div>

app/views/todo_lists/edit.html.erb
<h1>New To Do List</h1>

<%= render 'form' %>

app/views/todo_lists/new.html.erb
<div class = "form-wrapper">

	<h1 class = "form-header">New List</h1>

	<%= render 'form' %>

</div>

app/views/todo_lists/show.html.erb
<div class = "show-list group">

	<%= link_to "E", edit_todo_list_path(@todo_list), class: "list-delete", todo_list: @todo_list %>
	<%= link_to "X", todo_list_path(@todo_list), method: :delete, class: "list-delete" %>

	<br>

	<div class = "list-header group">
		<p class = "list-title"><%= @todo_list.title %></p>
		<p class = "list-type"><%= @todo_list.list_type %></p>
	</div>

	<%= form_for [@todo_list, @todo_item] do |f| %>
		
		<%= f.text_field :content, class: "show-new_item_box" %>
		<%= f.submit "+", class: "new_item_box_submit" %>

	<% end %>
	<br>

	<% @todo_list.todo_items.where('checked = 0').each do |todo_item| %>

		<%= render 'todo_items/todo_item', todo_item: todo_item, todo_list: @todo_list %>

	<% end %>

</div>